### ISSUE TITLE
Backup fail since upgrade : disappearance of option -b

### ISSUE THREAD

**Issue by tomdereub** [ashemsay/restic_ynh#1]
Same issue in borg package, seems fixed by : https://github.com/YunoHost-Apps/borg_ynh/pull/43
Just make this change in conf/backup-with-restic.j2 : 

- for app in $(yunohost app list --installed -b | grep id: | cut -d: -f2); do
+ for app in $(ls /etc/yunohost/apps/*/scripts/backup | cut -d / -f 5); do

(sorry, I don't know how to make a commit myself, I'm no dev...)

**Comment by ashemsay** [comment]
Merci pour l'info, je suis en train de tester ça

**Comment by tomdereub** [comment]
I've tested it on my server, and it works.

**Comment by ashemsay** [comment]
I started working on it, hopefully I'll finish it this week-end.

**Comment by moutonjr** [comment]
Seems merged in Master (46c547c4fb7b8e8e90f7c95513ef26c2e7e43b24), shall we increment minor version and close this issue?

**Comment by ashemsay** [comment]
You're right, I had already incremented ynh version (from ynh5 to ynh6) regarding this.
