### ISSUE TITLE
support aarch64 architecture

### ISSUE THREAD

**Issue by oiseauroch** [ashemsay/restic_ynh#16]
la fonction pour la découverte des architecture ne prend pas en compte les architecture arm 64bits. (j'ai une rockpro avec un armbian 64bits)
J'ai fait une pull request dans le repo de yunohost-apps pour ajouter ce support.

**Comment by ashemsay** [comment]
Merci pour ton retour @oiseauroch, que renvoie la commande `uname -m`? C'est le retour de cette commande que je teste pour savoir quelle version de l'application télécharger

**Comment by oiseauroch** [comment]
Elle me renvoi "aarch64" mais comme je le disais plus haut, j'ai fait une pull request ici https://github.com/YunoHost-Apps/restic_ynh/pull/5

**Comment by ashemsay** [comment]
Je suis désolé, tout était dans ton premier message de trois lignes et j'ai trouvé le moyen de passer à côté -_-
Je m'en occupe.

**Comment by oiseauroch** [comment]
Il n'y a pas de mal, merci beaucoup.

**Comment by ashemsay** [comment]
C'est mergé (a4ec6bd), comme je le disais sur la PR, si la version n'est pas encore dispo (0.12.0~ynh9) utilise la commande `yunohost app install https://github.com/YunoHost-Apps/restic_ynh/tree/master` ou utilise l'URL dans l'interface web.
