### ISSUE TITLE
Mail incomplete, marked as Success even if it fails

### ISSUE THREAD

**Issue by tomdereub** [ashemsay/restic_ynh#19]
The mail that is send at every backup doesn't work well : 
- when backup succeed, I get a line for each successful backup (data, app, etc...)
- when a backup fails, I get no line. If the whole backup fails, I get a blank mail, with success in the title

I've re-intalled the app from scratch and I get the same behaviour.
There has been some changes on borg app, and mails are working very well, maybe you could do the same way ?

**Comment by ashemsay** [comment]
Hi, yes I know there is a lot of things to fix with those e-mails.
Don't have much time to handle this right now, can't promise anything.

**Comment by tomdereub** [comment]
Would be solved by https://github.com/ashemsay/restic_ynh/issues/22.
