### ISSUE TITLE
Restic server

### ISSUE THREAD

**Issue by KvL159** [ashemsay/restic_ynh#2]
Would you consider make a package for the server, similar to what Borg has :
https://github.com/YunoHost-Apps/borgserver_ynh/tree/

**Comment by ashemsay** [comment]
I chose to use restic instead of borg specifically because it doesn't need a server package, only a sftp server.
I suggest you go through the readme, if there are some things to clarify let me know but I won't make a server package.

**Comment by KvL159** [comment]
Ok understoodn thank you for the feedback !
