### ISSUE TITLE
Too verbose restic mail report

### ISSUE THREAD

**Issue by moutonjr** [ashemsay/restic_ynh#4]
Hello,

My restic mail report is the only way to get me information about the restic status.

It's synchronous (=super heavy) and, as resulting logs are verbose, mail report is illisible (UTF-8 encoding failures, 400-lines logs)

Best would be :
* To gather in variable all the stderr
* To gather backup exit codes of all components
* To sum up in report all statuses and, below, errors that could have happened.

What are your feedbacks about the improvement?

**Comment by ashemsay** [comment]
You're right, the logs are messy and those are good ideas.
I just don't know when I'll do it.

**Comment by ashemsay** [comment]
I started working on it, you can try branch `feat/summarize-logs`.
Here's an example of what the new log looks like:

Subject: `YunoHost Restic backup log on ${server} (SUCCESS)`  # or `(FAIL)` although I never got the fail message yet

Content:
```
conf_cron: Success
conf_ldap: Success
conf_nginx: Success
conf_ssh: Success
conf_ssowat: Success
conf_xmpp: Success
conf_ynh_certs: Success
conf_ynh_currenthost: Success
conf_ynh_firewall: Success
data_home: Success
data_mail: Success
gitlab-runner: Success
keeweb: Success
```
It's a quick and dirty grep but does the trick.

**Comment by ashemsay** [comment]
I merged it, if you feel like suggesting more on the topic feel free to open a new issue.
