### ISSUE TITLE
Settings in Yunohost are not used.

### ISSUE THREAD

**Issue by moutonjr** [ashemsay/restic_ynh#5]
When we install restic_ynh, several options are specified, that are later hard-coded in the scripts. Passphrase, server, port (which is never used btw), path.

When changed with `yunohost app setting restic port -v 4567`, it doesn't change hardcoded values.

**Comment by moutonjr** [comment]
See PR #6 (withstanding you struggle with dev time ;) )

**Comment by ashemsay** [comment]
Merged your PR #6
